name: The PK3s

on:
  push:
    paths-ignore:
        - '**.md'
        - '.github/**'
        - '.gitignore'
        - '.vscode/**'
  pull_request:
    paths-ignore:
        - '**.md'
        - '.github/**'
        - '.vscode/**'
        - '.gitignore'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set current date as env variable # pacola if coyping from https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows was a challenge:
      run: echo "NOW=$(date +%Y-%m-%d)" >> $GITHUB_ENV

    - name: get us a pk3
      run: |
        cd src/
        zip -r ../bubsy-${{ env.NOW }}.pk3 .
    
    - name: send thing to the action tab
      uses: actions/upload-artifact@v4
      id: artifact-upload
      with:
        name: bubsy
        path: bubsy-${{ env.NOW }}.pk3

    - name: send the artifact link :P
      uses: "amozeo/action-discord-md-publish@main"
      with:
        file: "FEATURES.md"
        webhook: ${{ secrets.DISCORD_WEBHOOK }}

    - name: could you preetty please send the file to the discord
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: bubsy-${{ env.NOW }}.pk3

    - name: gives us the commits pleaaase
      uses: Sniddl/discord-commits@v1.6
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: "Successful commit to **${{ github.ref_name }}**"
        template: "avatar-with-link"
        include-extras: true
